# Default values for AzDOAgentHelm.
# This is a YAML-formatted file.

azdo:
  pat: "!AZDO_PAT_TOKEN!"
  url: 'https://dev.azure.com/rmoreiraoms'
  pool: 'k8skeda'

container:
  registryUrl: 'acraksinadayrmoreirao.azurecr.io'
  imageName: 'azdowin'
  imageTag: 'latest'
